version: '3.7'

services:
  node-exporter:
    container_name: node-exporter
    image: quay.io/prometheus/node-exporter
    container_name: node-exporter
    hostname: node-exporter
    restart: always
    ports:
      - "9100:9100"
